language: ruby

#bundler_args: --without development

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get -qq install syslog-ng puppet
  - bundle install

before_script:
  - mkdir -p ~/.puppet/modules
  - ln -s $PWD ~/.puppet/modules/patterndb
  - git clone https://github.com/puppetlabs/puppetlabs-stdlib ~/.puppet/modules/stdlib

script:
  - bundle exec rake SPEC_OPTS='--format documentation'
  - ./smoke/test

rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.1

env:
  matrix:
    - PUPPET_GEM_VERSION="~> 2.7.0" FACTER_GEM_VERSION="~> 1.6.0"
    - PUPPET_GEM_VERSION="~> 2.7.0" FACTER_GEM_VERSION="~> 1.7.0"
    - PUPPET_GEM_VERSION="~> 3.0"
    - PUPPET_GEM_VERSION="~> 3.1"
    - PUPPET_GEM_VERSION="~> 3.2"
    - PUPPET_GEM_VERSION="~> 3.3"
    - PUPPET_GEM_VERSION="~> 3.4"
    - PUPPET_GEM_VERSION="~> 3.5"

matrix:
  fast_finish: true
  exclude:
    - rvm: 2.1.1
      env: PUPPET_GEM_VERSION="~> 2.7.0" FACTER_GEM_VERSION="~> 1.6.0"
    - rvm: 2.1.1
      env: PUPPET_GEM_VERSION="~> 2.7.0" FACTER_GEM_VERSION="~> 1.7.0"
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 2.7.0" FACTER_GEM_VERSION="~> 1.6.0"
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 2.7.0" FACTER_GEM_VERSION="~> 1.7.0"
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="~> 2.7.0" FACTER_GEM_VERSION="~> 1.6.0"
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="~> 2.7.0" FACTER_GEM_VERSION="~> 1.7.0"
    - rvm: 1.8.7
      env: PUPPET_GEM_VERSION="~> 3.2.0"

notifications:
    email:
      recipients:
        - wernli@in2p3.fr
      on_success: change
      on_failure: always
